version: '2'

services:
  hello-world:
    build: .
    volumes:
      - ${PWD}/logs:/app/logs
      - ${PWD}/HelloWorld:/go/src/app
    command: ["run.sh"]

  list:
    build: .
    volumes:
      - ${PWD}/logs:/app/logs
      - ${PWD}/List:/go/src/app
    command: ["run.sh"]

